spring.application.name=PeerTube

#Cambiar el puerto en las otras a 8081 y 8082.
server.port=8080

#Se pone el /videos porque todos los datos se acceden a través de los videos, y así no hay que ponerlo en cada consulta.
peertube.url=https://peertube3.cpy.re/api/v1
